spring.application.name=authentication-rbac
spring.data.mongodb.uri=mongodb+srv://prabeshsuwal1234:Kathmandu-123@cluster0.1teqdim.mongodb.net/rbac
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Permission Sync Configuration
permission.sync.cron=0 0 * * * *
permission.sync.notification.emails=prabeshsuwal1234@gmail.com

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sbsolutionstest@gmail.com
spring.mail.password=fblvdgrivboiihpq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true