spring.application.name=authentication-rbac
spring.data.mongodb.uri=mongodb+srv://prabeshsuwal1234:Kathmandu-123@cluster0.1teqdim.mongodb.net/rbac
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.data.mongodb.core.MongoOperations=DEBUG

# Permission Sync Configuration
permission.sync.cron=0 0 * * * *
permission.sync.notification.emails=prabeshsuwal1234@gmail.com

# Role Sync Configuration
role.sync.cron=0 1 * * * *

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sbsolutionstest@gmail.com
spring.mail.password=fblvdgrivboiihpq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Jackson Configuration
spring.jackson.time-zone=Asia/Kathmandu
#spring.jackson.property-naming-strategy=SNAKE_CASE
#spring.jackson.serialization.write-dates-as-timestamps=false
#spring.jackson.deserialization.fail-on-unknown-properties=false

# Actuator Endpoints
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

# Server Configuration
server.port=8080

# JWT Configuration
app.jwt.secret=my_super_secret_key_that_is_long_enough_to_meet_HS512_requirements_1234
app.jwt.expiration=86400
app.jwt.refresh-expiration=604800

# Logging Configuration
logging.level.com.sb.authenticationrbac=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG

# Cache Configuration
spring.cache.type=simple
